ground_segmentation:
  ros__parameters:
    n_threads: 4                # number of threads to use.

    r_min: 0.3 # minimum point distance.
    r_max: 30 # maximum point distance.
    n_bins: 180 # number of radial bins.
    n_segments: 360 # number of radial segments.

    sensor_height: 0.0 # sensor height above ground. 修改你的雷达高度
    min_slope: 0.0 # minimum slope of a ground line.
    max_slope: 0.5 # maximum slope of a ground line.
    max_fit_error: 0.006 # maximum error of a point during line fit.
    max_dist_to_line: 0.06 # maximum vertical distance of point to line to be considered ground.
    long_threshold: 1.0 # distance between points after which they are considered far from each other.
    max_long_height: 0.3 # maximum height change to previous point in long line.
    max_start_height: 0.52 # maximum difference to estimated ground height to start a new line.
    # 0.52 是能上环高的一个测试值
    line_search_angle: 0.2 # how far to search in angular direction to find a line [rad].

    gravity_aligned_frame: "camera_init"   # Frame which has its z axis aligned with gravity. (Sensor frame if empty.)

    latch: false                # latch output topics or not
    visualize: false            # visualize segmentation result - USE ONLY FOR DEBUGGING

    input_topic: "/cloud_registered_body"  # input pointcloud topic
    obstacle_output_topic: "/segmentation/obstacle"
    ground_output_topic: "/segmentation/ground"